### ISSUE TITLE
Expose new m3 cumulative volume sensors for gas meter

### ISSUE THREAD

**Issue by robhawkes** [megakid/ha_hildebrand_glow_ihd_mqtt#10]
Hildebrand have added new sensors to the gas meter MQTT payload that expose raw m3 readings for meters that record in m3 units:
- `cumulativevol`
- `cumulativevolunits`
- `dayvol`
- `weekvol`
- `monthvol`
- `dayweekmonthvolunits`

These were added after I contacted their support about [inconsistencies with my gas readings](https://github.com/megakid/ha_hildebrand_glow_ihd_mqtt/issues/6). As a result they updated the firmware with the following changes:
- Resolved issue where gas meter readings (for me) were out by billions of kWh
- Added new sensors with raw m3 units

Can these be added to the integration so they can be collected and used by Home Assistant? 🙏

New payload as of today, pulled from the MQTT feed from my own CAD:
```
{
  "gasmeter": {
    "timestamp": "2022-06-30T13:53:28Z",
    "energy": {
      "import": {
        "cumulative": 2713.756,
        "day": 2.591,
        "week": 17.044,
        "month": 244.627,
        "units": "kWh",
        "cumulativevol": 244.238,
        "cumulativevolunits": "m3",
        "dayvol": 2.591,
        "weekvol": 17.044,
        "monthvol": 244.627,
        "dayweekmonthvolunits": "kWh",
        "mprn": "---",
        "supplier": "---",
        "price": {
          "unitrate": 0.0736,
          "standingcharge": 0.2722
        }
      }
    }
  }
}
```

It looks like the day, week and month vol values are still in kWh so I will contact their support about this. Though in any case it would still be good to have them exposed via the integration.

**Comment by andyvee69** [comment]
They have also removed the gas export and gas power fields

**Comment by megakid** [comment]
@andyvee69 Great job helping them get better stats out for the gas meter!

Do you happen to know if the IHD will auto-update to this firmware or does it need to be triggered?  Please can you post your STATE message so I can see what software version your device is reporting?  It might be necessary to change the integration behaviour based on what version it sees.

**Comment by andyvee69** [comment]
@megakid I think you meant to tag @robhawkes 

Firmware version is now 1.8.13 though and clivee is rolling out to everyone starting at 07:30 this morning
