### ISSUE TITLE
Electric standing charge missing 

### ISSUE THREAD

**Issue by Xboxcarl** [megakid/ha_hildebrand_glow_ihd_mqtt#13]
Hello, firstly awesome work !! 

I have a issue..  I’m not pulling over the electric standing charge - state unknown.  I’m really new to this so likely something I have done wrong.  Can anyone help ?
![053EB0BA-31A0-4B5C-BF3D-5AB833D1D9E6](https://user-images.githubusercontent.com/108306279/178136716-f5f6bd82-2f3c-4e66-bd16-70a205fff59c.jpeg)

**Comment by megakid** [comment]
Strange. Must not be coming through from your meter- does the IHD show it?

**Comment by Xboxcarl** [comment]
Hello, sorry for delay. Been on holiday…. This resolved itself after 2 days of the smart meter not working. It came back to life and is now working.  The IHD was displaying.
