### ISSUE TITLE
Installed Via HACS not showing in integration

### ISSUE THREAD

**Issue by ademobile** [megakid/ha_hildebrand_glow_ihd_mqtt#17]
Either I am being dumb and not understanding something, however I have installed via HACS (using readme infromation) and restarted (and rebooted) HA, however the ingegration does not show when I try to add it. I have searched every part of the name i.e. hildebrand, glow and mqtt. Yet nothing is shown. What am I doing wrong, as I am stumped!

Thanks

**Comment by ademobile** [comment]
Removed integration from HACS, re-added it and still made no difference. Tried another restart and still nothing. Just tried again and its there - no idea as did nothing!

**Comment by brewston** [comment]
When I've had problems finding integrations installed by HACS, clearing my browser cache helped. ctrl+F5 in firefox.
