### ISSUE TITLE
No handling for multirate electricity costs.

### ISSUE THREAD

**Issue by JSladen** [megakid/ha_hildebrand_glow_ihd_mqtt#18]
Hi,

I am having an issue where the cost of electricity imported is incorrect.

It appears to be doing a straight 'standing charge' + 'usage today' x 'unit cost', so the is no handling of multirate metering.

Shouldn't it be more along the lines of 'daily cost' = 'previous daily cost' + ('daily kWh' - 'previous daily kWh') x 'current unit cost' ? The standing charge will need handling as well.

This way should work for any kind of Economy 7/Economy 4/Variable/Flexible rate tarriff, and be correct.

Cheers
James

**Comment by deangoldhill** [comment]
Yes I think I am having the same issue. I am on Octopus go which gives a rate of £0.07 between 12:30 and 04:30.
Just after 04:30, there is a big jump in the cost sensor within just a few minutes. Prior to that it is calculating the correct cost at the cheap rate.
what I think is happening is, at the point the cost sensor goes back to the normal rate, it is recalculating the cost for period during which the rate is lower. So when looking at the daily cost at any point after 04:30, it is based on the whole day being at the higher rate.
![cost-today](https://user-images.githubusercontent.com/8200187/204130830-0967c431-6b00-402d-8f5f-535cec63d858.PNG)
![import-today](https://user-images.githubusercontent.com/8200187/204130831-e716c8cb-6b98-4d15-b431-b893672da61a.PNG)

**Comment by Bilgeratty** [comment]
Yeah; just finished installing your super integration...Kudos for that!  But although most things look spot-on, the day's electricity costs were scary (£4+ instead of £1.70)...  I too am using Octopus GO cheap rate extensively to charge a battery and heat water etc during the 7p overnight period.

**Comment by ZionFox** [comment]
I can confirm this issue still exists. It still has a jump up when the unit rate changes. The in-home display proper is showing a different money value than what is being calculated here.

Is there any update on resolving this, @megakid?

**Comment by dannytsang** [comment]
A feature request to add this to into the MQTT message would be best. The display i believe shows the right value so if they send that as part of the message then it would be easier for the integration. I have sent an email to support to ask for this.

**Comment by megakid** [comment]
This integration will only show information it receives from the IHD.  If your IHD is incorrect, then this integration's sensors will also be incorrect.
