### ISSUE TITLE
Question: Cost sensors?

### ISSUE THREAD

**Issue by robertalexa** [megakid/ha_hildebrand_glow_ihd_mqtt#2]
Hi James,

Lovely work you have done here, I was truly looking into how to do this, but I am super close to a 4 week long car roadtrip, so all my energy is aimed at that, it would have been a project for when I was coming back. Glad to see someone starting this!! So I will deffo study your code more in depth as a learning process for me, and to be honest, once I get my setup moved to using the integration I will offer the support and any work needed as Pull Requests to your project.

My question, do you intend to add the cost template sensors, I've had a quick skim read of the code and I couldn't see anything about it?

By the way, this is my Github account, if you want to link my profile in your project description (readme)

Good work once more!

**Comment by megakid** [comment]
Thanks @robertalexa - as you can probably see with the code, I essentially copy pasted your template sensors yaml definitions and reformatted them as Python dicts!  Any questions on the code you have, let me know!

I have now added the cost sensors in v1.3!
