### ISSUE TITLE
Gas sensors not updating so often now

### ISSUE THREAD

**Issue by megavar** [megakid/ha_hildebrand_glow_ihd_mqtt#21]
After successfully installing this integration via HACS I was pleased to see everything up and running so quick.

However after a couple of days the gas sensors have almost stopped updating.  For example 'smart_meter_gas_import_vol_today' is now only sporadically updating.  All other sensors and data are flowing as normal.  

Any ideas where to look first?

Thanks.

**Comment by megakid** [comment]
This integration will only show information it receives from the IHD. If your IHD is incorrect, then this integration's sensors will also be incorrect.  

Without further information, I'd have to conclude that your smart meter is having issues sending data to the IHD.
