### ISSUE TITLE
Add ability to configure topic prefix instead of hardcoded "glow"

### ISSUE THREAD

**Issue by photomoose** [megakid/ha_hildebrand_glow_ihd_mqtt#24]
My Hildebrand Glow IHD publishes messages with a topic name prefix of "energy" instead of "glow". 

I manually edited the `data_topic` variable sensor.py on my local installation and the IHD was successfully found. (See https://github.com/megakid/ha_hildebrand_glow_ihd_mqtt/blob/main/custom_components/hildebrand_glow_ihd_mqtt/sensor.py#L283)

Could this be made into a configuration setting?

**Comment by megakid** [comment]
Is this a new IHD? Or did you manually change it? I could expose this as a config option for sure.

**Comment by RexNoctis** [comment]
Fantastic, thanks for the update!
