### ISSUE TITLE
Would it be possible to add sensor.smart_meter_electricity_export_today

### ISSUE THREAD

**Issue by wawyed** [megakid/ha_hildebrand_glow_ihd_mqtt#27]
Would be great to able to to track my daily export through the smart meter.

Thanks a lot.

**Comment by megakid** [comment]
This integration will only show information it receives from the IHD.  Unlike 'import', 'export' is only given as a cumulative total.  Use a "Utility Meter" helper to split it into days, weeks etc: https://www.home-assistant.io/integrations/utility_meter/
