### ISSUE TITLE
Smart Meter Electricity: Cost (Today) jumps about £2 when switch from Economy 7 rate to normal

### ISSUE THREAD

**Issue by dolphinituk** [megakid/ha_hildebrand_glow_ihd_mqtt#28]
Been using for a week or so an noticed that the Cost per day was well out

Looking at the graph for Smart Meter Electricity: Cost (Today) there is a jump about 7:30am when my electric rate changes from Economy 7 to normal

![Screenshot 2023-02-06 160026](https://user-images.githubusercontent.com/18261453/217021737-77da859b-efd7-474b-a012-0e9ac8e95515.png)

**Comment by dannytsang** [comment]
I have just checked my unit and I can confirm the above.

**Comment by megakid** [comment]
It was probably a mistake to include this sensor.  It's not trivial to track this type of thing when the current logic just takes exactly what the IHD gives it and displays as HA sensors.  I am probably going to keep this sensor but add a note to the README file.
