### ISSUE TITLE
Meter Error filtering

### ISSUE THREAD

**Issue by PhillyGilly** [megakid/ha_hildebrand_glow_ihd_mqtt#3]
Thanks for this integration. 
The problem I have is that my meter is sending readings to the CAD that are low by a factor of 10^3. So it is reading 0.006kWh when it should be reading 6kWh.
![image](https://user-images.githubusercontent.com/56273663/174057500-ab34d8b5-018c-4ce1-9a75-77968c4a1342.png)
Obviously I have raised the issue with my supplier but they're not super interested as the stuff going to them for billing - and confirmed on the Bright app - is working. I can't be the only person with this problem unless each SMETS2 meter is configured individually.
Any chance of an otion to fix the meter error in the integration config?

**Comment by megakid** [comment]
Sure. I'll add a scaling number you can configure!

**Comment by megakid** [comment]
What metrics do you want scaled by this number?  Is it all the electricity ones that are measured in kW or kWh?  Or gas too?

**Comment by PhillyGilly** [comment]
I can't test the gas, but the meter appears to be measuring electricity in MWh which the Glow thinks is kWh.
Here is a picture of yours left mine right.
![image](https://user-images.githubusercontent.com/56273663/174134552-036c10c5-dd69-4d30-86db-0fed64715834.png)
(while I was about it I made a couple of preference tweaks to GBP/£/p usage!)
