### ISSUE TITLE
errs in log files

### ISSUE THREAD

**Issue by SteveBrailsord** [megakid/ha_hildebrand_glow_ihd_mqtt#30]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:608
Integration: Sensor (documentation, issues)
First occurred: 08:28:05 (2 occurrences)
Last logged: 08:28:05

Sensor sensor.smart_meter_ihd_software_version has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: v1.8.13 (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.smart_meter_ihd_hardware has device class None, state class measurement and unit None thus indicating it has a numeric value; however, it has the non-numeric value: GLOW-IHD-01-1v4-SMETS2 (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:503
Integration: Sensor (documentation, issues)
First occurred: 08:28:05 (6 occurrences)
Last logged: 08:28:05

Entity sensor.smart_meter_electricity_import_standing_charge (<class 'custom_components.hildebrand_glow_ihd.sensor.HildebrandGlowMqttSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.smart_meter_electricity_cost_today (<class 'custom_components.hildebrand_glow_ihd.sensor.HildebrandGlowMqttSensor'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.smart_meter_gas_import_unit_rate (<class 'custom_components.hildebrand_glow_ihd.sensor.HildebrandGlowMqttSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.smart_meter_gas_import_standing_charge (<class 'custom_components.hildebrand_glow_ihd.sensor.HildebrandGlowMqttSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Entity sensor.smart_meter_gas_cost_today (<class 'custom_components.hildebrand_glow_ihd.sensor.HildebrandGlowMqttSensor'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by capandcamera** [comment]
Getting the same errors

**Comment by jone9618** [comment]
Me too
