### ISSUE TITLE
REQUEST: Zero Value filtering

### ISSUE THREAD

**Issue by andyvee69** [megakid/ha_hildebrand_glow_ihd_mqtt#4]
I keep getting zero values on the unit rates and standing charges periodically.

Can you add the
`"ignore_zero_values": True,`
by default to these sensors as well please

Please don't add this to the daily, weekly, monthly import sensors as it will mess these up when they reset

**Comment by megakid** [comment]
Want to raise a PR?

You can just edit it directly in GitHub by clicking the edit button (top
right when viewing the sensor.py file)

**Comment by andyvee69** [comment]
I think I've done that correctly .....

**Comment by megakid** [comment]
Looks good! nice one

**Comment by andyvee69** [comment]
Thanks :)
Just wish the Glow wouldn't keep sending so many zero values on the gas - it seems to keep dropping off of the HAN
