### ISSUE TITLE
Error adding entities for domain sensor with platform hildebrand_glow_ihd

### ISSUE THREAD

**Issue by holdestmade** [megakid/ha_hildebrand_glow_ihd_mqtt#45]
Getting this on startup in HA 2023.11.

Assume this needs changing in `sensor.py` (tried and works, puts them all to the sensor category)

`entity_category = EntityCategory.CONFIG` to `entity_category = None`

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 09:19:08 (1 occurrences)
Last logged: 09:19:08

```
Error adding entities for domain sensor with platform hildebrand_glow_ihd
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.smart_meter_electricity_export cannot be added as the entity category is set to config
```

**Comment by donaldwpage** [comment]
Agree this appears to fix the error

**Comment by holdestmade** [comment]
> Installed the latest integration update today (1.6.3), but the category errors remain. Curious as to why this fix wasn't included?

The PR hasn't been merged by the codeowner

**Comment by holdestmade** [comment]
No, not sure, other changes were merged 4 days ago

**Comment by Blackduke77** [comment]
Can anyone review it, I have a review button and a comment box.

**Comment by kabadisha** [comment]
I have just reviewed the PR, but I think it requires one of the maintainers to review it before the PR will be merged.
