### ISSUE TITLE
Incorrect sensor state_class

### ISSUE THREAD

**Issue by jernauH** [megakid/ha_hildebrand_glow_ihd_mqtt#46]
I’ve found that on the HA energy dashboard that following a tariff change from my energy supplier the historical gas and electric costs were no longer being calculated. Looking at the electricty_import_unit_rate, gas_import_unit_rate, electricty_import_rate_standing_charge & gas_import_rate_standing_charge they are all set to state_class NONE when they should be state_class MEASUREMENT so that they are are added to HA’s long term stats database to enable the historical energy calculations to be carried out.

Can this be updated or is my setup incorrect with energy dashboard & the glow integration, is anyone else seeing historical costs broken following a tariff update to your smart meter?

**Comment by megakid** [comment]
Fixed in v1.7.1
